### ISSUE TITLE
moment.js errors in console, card not showing

### ISSUE THREAD

**Issue by mrmonat** [nova-cards/SystemInformationCard#1]
Hey I just installed your package, but when I visit my dashboard the Card is not showing. Instead I found this error message multiple times in the Browser Console:

![image](https://user-images.githubusercontent.com/17597850/44588106-2109a700-a7b5-11e8-8041-108f44c813b1.png)

**Comment by schaeftide** [comment]
thanks for reporting this issue,
it should be fixed right now
