### ISSUE TITLE
Memory Used - wrong value

### ISSUE THREAD

**Issue by iDevelopThings** [nova-cards/SystemInformationCard#2]
It seems like it is returning the amount not in use.

![image](https://user-images.githubusercontent.com/4105581/44597857-f6c1e480-a7c8-11e8-8137-211b2766a8b6.png)

If you look and do the math, it seems about right

**Comment by schaeftide** [comment]
Thanks for reporting. Indeed the used value of the memory was wrong. Should be fixed right now
